Changes done for Leave Community Functionalty
Binilkks/bgc-client-app pull request #50
Opened 2021-12-26 17:18 UTC by anusha880

1) Changes done to Leave community Under Communities Tab
2) Leave Community CSS Changes
3) Changes done to Join the Community.

2021-12-26 19:45 UTC, Binilkks requested changes

2021-12-26 19:45 UTC, Binilkks commented on src/redux/actions/dataActions.js
> +        dispatch(getPostsOfCommunity(newCommunity)),
Why do we need promise. all here ?

2021-12-26 19:46 UTC, Binilkks commented on src/redux/actions/dataActions.js
> +        dispatch(getPostsOfCommunity(newCommunity)),
Squash all the commits before raising PR , there should be only one commit in the PR

2021-12-27 14:48 UTC, anusha880 commented on src/redux/actions/dataActions.js
> +        dispatch(getPostsOfCommunity(newCommunity)),
Okay, Binil. Will do that into one.

2021-12-27 14:49 UTC, closed without merging